name: Run Shell Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        env:
          NAMES: ${{ vars.NAMES }}
        run: echo "NAMES=$NAMES"

      - name: Change directory to deploy and run shell script
        run: |
          cd deploy
          chmod +x generate_names.sh
          ./generate_names.sh 
