name: CI

on:
  workflow_dispatch

env:
  super_secret: ${{ secrets.ABCDE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          sudo mkdir /my_account
          sudo chmod -R 777 /my_account
          cd /my_account
          git clone https://github.com/newstartao/devops-testing
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Get /pwd
        run: |
          cd /my_account
          pwd
          echo "testing"
        

      - name: Run my build script
        run: |
          cd /my_account/devops-testing/deploy/
          bash ./test.sh 
