name: CI

on:
  workflow_dispatch

env:
  super_secret: ${{ secrets.devops.ABCDE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: newstartao/devops-testing
          token: ${{ secrets.devops.TOKEN }}

      - name: Setup working directory
        run: |
          sudo mkdir /my_account
          sudo chmod -R 777 /my_account
          cd /my_account

      - name: Get /pwd
        run: |
          cd /my_account
          pwd
          echo "testing"

      - name: Run my build script
        run: |
          cd /my_account/devops-testing/deploy/
          ./test.sh /my_account/devops-testing/deploy/values.yaml
