name: CI

on:
  workflow_dispatch:

env:
  super_secret: ${{ secrets.SERVER }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run my build script
        run: |
          bash test.yml && cat test.yml
          cat values.yaml
