name: CI

on:
  workflow_dispatch

env:
  super_secret: ${{ secrets.ABCDE }}
  token: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          sudo mkdir /my_account
          sudo chmod -R 777 /my_account
          cd /my_account
          git clone https://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@github.com/newstartao/devops-testing
          

      - name: Setup working directory
        run: |
          sudo mkdir /my_account
          sudo chmod -R 777 /my_account
          cd /my_account

      - name: Get /pwd
        run: |
          cd /my_account
          pwd
          echo "testing"

      - name: Run my build script
        run: |
          cd /my_account/devops-testing/deploy/
          ./test.sh /my_account/devops-testing/deploy/values.yaml
