name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: devops
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run my build script
        run: |
          bash deploy/test.sh && cat deploy/test.sh
          cat deploy/values.yaml
          echo"${{ env.tool }}"
          echo"${{ env.test }}"
        env:
          tool: ${{ secrets.SERVER }}
          test: ${{ vars.TEST }}
